using System.Text.Json;
using DreamCleaningBackend.Data;
using DreamCleaningBackend.DTOs;
using DreamCleaningBackend.Helpers;
using DreamCleaningBackend.Models;
using DreamCleaningBackend.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Xunit;

namespace DreamCleaningBackend.Tests
{
    /// <summary>
    /// CROSS-SURFACE EQUIVALENCE: frontend calculator == backend calculator.
    ///
    /// pricing-fixtures.json is generated by the REAL frontend module
    /// (DreamCleaningNG/src/app/shared/pricing/order-pricing.calculator.ts), compiled and executed,
    /// using the production configuration exported from the admin panel on 2026-08-02. Every row
    /// is then recomputed here through the REAL backend path — OrderPricingInputBuilder loading
    /// from a real ApplicationDbContext, then OrderPricingCalculator — and asserted identical.
    ///
    /// This is the check that catches mirror drift. A price the booking page shows but the server
    /// does not charge is the single most damaging failure this codebase can produce, and it is
    /// exactly what Defect 1 was: the builder silently dropped five fields plus the price floor,
    /// so the whole backend priced under the pre-refactor model while the UI used the new one.
    ///
    /// To regenerate after a pricing change, re-run the generator against the frontend module and
    /// re-export the configuration from the admin panel. Never hand-edit this JSON to make a
    /// failing test pass — a mismatch means the two calculators genuinely disagree.
    /// </summary>
    public class CrossSurfaceEquivalenceTests : IDisposable
    {
        private const int ResidentialId = 1;
        private const int MoveInOutId = 2;
        private const int DeepCleaningId = 100;

        // Per-service-type ids so both types own their own bedrooms/bathrooms/sqft services,
        // exactly as production does.
        private static int BedroomsId(int serviceTypeId) => serviceTypeId * 100 + 1;
        private static int BathroomsId(int serviceTypeId) => serviceTypeId * 100 + 2;
        private static int SqftId(int serviceTypeId) => serviceTypeId * 100 + 3;
        private static int LevelsId(int serviceTypeId) => serviceTypeId * 100 + 4;

        private static readonly (int Quantity, decimal Included)[] SqftThresholds =
        {
            (0, 400m), (1, 650m), (2, 850m), (3, 1000m), (4, 1500m), (5, 1800m), (6, 2000m)
        };

        private readonly ApplicationDbContext _context;

        public CrossSurfaceEquivalenceTests()
        {
            var options = new DbContextOptionsBuilder<ApplicationDbContext>()
                .UseInMemoryDatabase($"cross-surface-{Guid.NewGuid()}")
                .ConfigureWarnings(w => w.Ignore(InMemoryEventId.TransactionIgnoredWarning))
                .Options;

            _context = new ApplicationDbContext(options);
            SeedProductionConfiguration();
        }

        public void Dispose() => _context.Dispose();

        private void SeedProductionConfiguration()
        {
            // ── Residential Cleaning ──
            SeedServiceType(
                ResidentialId, "Residential Cleaning",
                basePrice: 90m, timeDuration: 120m, minimumPrice: 130m,
                bedroomTiers: Array.Empty<(decimal, decimal, decimal)>(),
                sqftTiers: new[] { (0m, 0.18m, 0.24m), (400m, 0.135m, 0.18m), (1200m, 0.11m, 0.145m) });

            // ── Move in/out Cleaning — note the bedroom RATE TIERS (0 → $45/60min, 1 → $22.50/30min) ──
            SeedServiceType(
                MoveInOutId, "Move in/out Cleaning",
                basePrice: 187.50m, timeDuration: 270m, minimumPrice: 245m,
                bedroomTiers: new[] { (0m, 45m, 60m), (1m, 22.50m, 30m) },
                sqftTiers: new[] { (0m, 0.18m, 0.24m), (400m, 0.12m, 0.16m), (1200m, 0.1125m, 0.15m) });

            _context.ExtraServices.Add(new ExtraService
            {
                Id = DeepCleaningId,
                Name = "Deep Cleaning",
                Price = 90m,
                Duration = 120m,
                PriceMultiplier = 1.5m,
                IsDeepCleaning = true,
                IsAvailableForAll = true,
                IsActive = true
            });

            _context.SaveChanges();
        }

        private void SeedServiceType(
            int serviceTypeId, string name, decimal basePrice, decimal timeDuration, decimal minimumPrice,
            (decimal From, decimal Cost, decimal Minutes)[] bedroomTiers,
            (decimal From, decimal Cost, decimal Minutes)[] sqftTiers)
        {
            _context.ServiceTypes.Add(new ServiceType
            {
                Id = serviceTypeId, Name = name, BasePrice = basePrice,
                TimeDuration = timeDuration, MinimumPrice = minimumPrice, IsActive = true
            });

            _context.Services.AddRange(
                new Service
                {
                    Id = BedroomsId(serviceTypeId), Name = "Bedrooms", ServiceKey = "bedrooms",
                    Cost = 22.50m, TimeDuration = 30m, ServiceTypeId = serviceTypeId,
                    InputType = "dropdown", IsActive = true,
                    ZeroQuantityCost = 0m, ZeroQuantityDuration = 0m
                },
                new Service
                {
                    Id = BathroomsId(serviceTypeId), Name = "Bathrooms", ServiceKey = "bathrooms",
                    Cost = 22.50m, TimeDuration = 30m, ServiceTypeId = serviceTypeId,
                    InputType = "dropdown", IsActive = true
                },
                new Service
                {
                    Id = SqftId(serviceTypeId), Name = "Sq.ft", ServiceKey = "sqft",
                    Cost = 0.18m, TimeDuration = 0.24m, ServiceTypeId = serviceTypeId,
                    InputType = "slider", IsActive = true, ChargeAboveThreshold = true
                },
                // Levels, seeded on BOTH residential-shaped types exactly as the migration does.
                // Zero-quantity columns stay null so the generic zero-quantity branch can never
                // hijack the line.
                new Service
                {
                    Id = LevelsId(serviceTypeId), Name = "Levels", ServiceKey = "levels",
                    Cost = 35m, TimeDuration = 25m, ServiceTypeId = serviceTypeId,
                    InputType = "dropdown", IsActive = true, ChargeAboveThreshold = true,
                    MinValue = 1, MaxValue = 4, StepValue = 1, DisplayOrder = 4
                });

            // The SELF-REFERENCING allowance: the levels service is its own threshold source, so
            // the first level is included and billable = max(0, levels - 1).
            _context.ServiceThresholds.Add(new ServiceThreshold
            {
                ServiceId = LevelsId(serviceTypeId),
                SourceServiceId = LevelsId(serviceTypeId),
                SourceQuantity = 1,
                IncludedQuantity = 1
            });

            foreach (var (quantity, amount) in SqftThresholds)
            {
                _context.ServiceThresholds.Add(new ServiceThreshold
                {
                    ServiceId = SqftId(serviceTypeId),
                    SourceServiceId = BedroomsId(serviceTypeId),
                    SourceQuantity = quantity,
                    IncludedQuantity = amount
                });
            }

            var order = 1;
            foreach (var (from, cost, minutes) in sqftTiers)
            {
                _context.ServiceRateTiers.Add(new ServiceRateTier
                {
                    ServiceId = SqftId(serviceTypeId),
                    FromQuantity = from, Cost = cost, TimeDuration = minutes, DisplayOrder = order++
                });
            }

            order = 1;
            foreach (var (from, cost, minutes) in bedroomTiers)
            {
                _context.ServiceRateTiers.Add(new ServiceRateTier
                {
                    ServiceId = BedroomsId(serviceTypeId),
                    FromQuantity = from, Cost = cost, TimeDuration = minutes, DisplayOrder = order++
                });
            }
        }

        /// <param name="Levels">
        /// Level count for a house; null for an apartment, which submits no levels line at all.
        /// A non-null value also makes the row a House, which is what lets the backend's
        /// property-type clamps run on the same input the frontend priced.
        /// </param>
        public record Fixture(
            string ServiceTypeName, int Bedrooms, int Bathrooms, int Sqft, bool DeepCleaning,
            int? Levels,
            decimal ExpectedSubTotal, decimal ExpectedDisplayDuration, bool ExpectedMinimumPriceApplied);

        private record FixtureFile(List<Fixture> Fixtures);

        public static IEnumerable<object[]> AllFixtures()
        {
            foreach (var fixture in LoadFixtures())
                yield return new object[] { fixture };
        }

        private static List<Fixture> LoadFixtures()
        {
            var path = Path.Combine(AppContext.BaseDirectory, "pricing-fixtures.json");
            if (!File.Exists(path))
                throw new FileNotFoundException(
                    "pricing-fixtures.json is missing. It is generated from the frontend calculator; " +
                    "see the class summary for how to regenerate it.", path);

            var json = File.ReadAllText(path);
            var parsed = JsonSerializer.Deserialize<FixtureFile>(json, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

            return parsed?.Fixtures ?? throw new InvalidOperationException("pricing-fixtures.json contained no fixtures.");
        }

        [Theory]
        [MemberData(nameof(AllFixtures))]
        public async Task Backend_ReproducesFrontendExactly(Fixture fixture)
        {
            var serviceTypeId = fixture.ServiceTypeName.StartsWith("Residential") ? ResidentialId : MoveInOutId;
            var serviceType = await _context.ServiceTypes.FirstAsync(st => st.Id == serviceTypeId);

            var dto = new CreateBookingDto
            {
                ServiceTypeId = serviceTypeId,
                // A levels row is a House, so the backend's property-type clamps run. Sending
                // House WITHOUT a levels line (the apartment rows) also has to be safe.
                PropertyType = fixture.Levels.HasValue ? PropertyDetailsHelper.House : null,
                Services = new List<BookingServiceDto>
                {
                    new() { ServiceId = BedroomsId(serviceTypeId),  Quantity = fixture.Bedrooms },
                    new() { ServiceId = BathroomsId(serviceTypeId), Quantity = fixture.Bathrooms },
                    new() { ServiceId = SqftId(serviceTypeId),      Quantity = fixture.Sqft }
                },
                ExtraServices = fixture.DeepCleaning
                    ? new List<BookingExtraServiceDto> { new() { ExtraServiceId = DeepCleaningId, Quantity = 1 } }
                    : new List<BookingExtraServiceDto>()
            };

            if (fixture.Levels.HasValue)
                dto.Services.Add(new BookingServiceDto
                    { ServiceId = LevelsId(serviceTypeId), Quantity = fixture.Levels.Value });

            // THE REAL BACKEND PATH — the same builder every controller and service uses.
            // allowCustomPricing: false — these fixtures are all catalogue-priced bookings.
            var input = await OrderPricingInputBuilder.FromBookingDtoAsync(
                _context, serviceType, dto, allowCustomPricing: false);
            var quote = OrderPricingCalculator.CalculateQuote(input);

            var label = $"{fixture.ServiceTypeName} {fixture.Bedrooms}bd/{fixture.Bathrooms}ba/{fixture.Sqft}sqft " +
                        $"{(fixture.DeepCleaning ? "Deep" : "Regular")}" +
                        $"{(fixture.Levels.HasValue ? $"/{fixture.Levels}lv" : "/apt")}";

            Assert.True(fixture.ExpectedSubTotal == quote.SubTotal,
                $"{label}: subtotal — frontend {fixture.ExpectedSubTotal:0.00}, backend {quote.SubTotal:0.00}");

            Assert.True(fixture.ExpectedDisplayDuration == quote.DisplayDuration,
                $"{label}: duration — frontend {fixture.ExpectedDisplayDuration}, backend {quote.DisplayDuration}");

            Assert.True(fixture.ExpectedMinimumPriceApplied == quote.MinimumPriceApplied,
                $"{label}: floor applied — frontend {fixture.ExpectedMinimumPriceApplied}, backend {quote.MinimumPriceApplied}");

            Assert.Empty(quote.Warnings);
        }

        [Fact]
        public void FixtureFile_CoversBothServiceTypes_AndBothCleaningLevels()
        {
            var fixtures = LoadFixtures();

            Assert.Equal(100, fixtures.Count);
            Assert.Contains(fixtures, f => f.ServiceTypeName.StartsWith("Residential"));
            Assert.Contains(fixtures, f => f.ServiceTypeName.StartsWith("Move"));
            Assert.Contains(fixtures, f => f.DeepCleaning);
            Assert.Contains(fixtures, f => !f.DeepCleaning);
            Assert.Contains(fixtures, f => f.Bathrooms == 2);
            // Both Studio floors must be represented, or the floor is untested.
            Assert.Contains(fixtures, f => f.ExpectedMinimumPriceApplied);

            // Levels: apartments and all four house counts, on both service types.
            Assert.Contains(fixtures, f => f.Levels == null);
            foreach (var levels in new[] { 1, 2, 3, 4 })
                Assert.Contains(fixtures, f => f.Levels == levels);
            Assert.Contains(fixtures, f => f.Levels.HasValue && f.ServiceTypeName.StartsWith("Residential"));
            Assert.Contains(fixtures, f => f.Levels.HasValue && f.ServiceTypeName.StartsWith("Move"));
            Assert.Contains(fixtures, f => f.Levels.HasValue && f.DeepCleaning);
        }

        /// <summary>
        /// A one-level house must be priced identically to the same home as an apartment, on both
        /// service types and at both cleaning levels. This is the fixture-level statement of the
        /// rule the whole feature rests on: the price driver is stairs, not the property type, so
        /// a house with nothing to climb costs exactly what a flat costs.
        /// </summary>
        [Fact]
        public void FixtureFile_OneLevelHouse_MatchesTheEquivalentApartment()
        {
            var fixtures = LoadFixtures();
            var oneLevel = fixtures.Where(f => f.Levels == 1).ToList();

            Assert.NotEmpty(oneLevel);

            foreach (var house in oneLevel)
            {
                var apartment = fixtures.SingleOrDefault(f =>
                    f.Levels == null &&
                    f.ServiceTypeName == house.ServiceTypeName &&
                    f.Bedrooms == house.Bedrooms &&
                    f.Bathrooms == house.Bathrooms &&
                    f.Sqft == house.Sqft &&
                    f.DeepCleaning == house.DeepCleaning);

                Assert.True(apartment != null,
                    $"No apartment counterpart for {house.ServiceTypeName} {house.Bedrooms}bd/" +
                    $"{house.Bathrooms}ba/{house.Sqft}sqft deep={house.DeepCleaning}");

                Assert.Equal(apartment!.ExpectedSubTotal, house.ExpectedSubTotal);
                Assert.Equal(apartment.ExpectedDisplayDuration, house.ExpectedDisplayDuration);
            }
        }
    }
}
