// <auto-generated />
using System;
using DreamCleaningBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamCleaningBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250621131758_AddSpecialOffersSystem")]
    partial class AddSpecialOffersSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DreamCleaningBackend.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AptSuite")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("HasHours")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasQuantity")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAvailableForAll")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeepCleaning")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSameDayService")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSuperDeepCleaning")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ExtraServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8101),
                            Description = "Thorough cleaning of all surfaces and hard-to-reach areas",
                            DisplayOrder = 1,
                            Duration = 60,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "deep-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = true,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Deep Cleaning",
                            Price = 50m,
                            PriceMultiplier = 1.5m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8105),
                            Description = "Most intensive cleaning service available",
                            DisplayOrder = 2,
                            Duration = 120,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "super-deep-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = true,
                            Name = "Super Deep Cleaning",
                            Price = 100m,
                            PriceMultiplier = 2.0m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8108),
                            Description = "Get your cleaning done today",
                            DisplayOrder = 3,
                            Duration = 0,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "same-day.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = true,
                            IsSuperDeepCleaning = false,
                            Name = "Same Day Service",
                            Price = 75m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8110),
                            Description = "Interior window cleaning",
                            DisplayOrder = 4,
                            Duration = 20,
                            HasHours = false,
                            HasQuantity = true,
                            Icon = "window-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Window Cleaning",
                            Price = 15m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8113),
                            Description = "Spot cleaning of walls",
                            DisplayOrder = 5,
                            Duration = 30,
                            HasHours = false,
                            HasQuantity = true,
                            Icon = "wall-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Wall Cleaning",
                            Price = 20m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8115),
                            Description = "Professional organizing of your space",
                            DisplayOrder = 6,
                            Duration = 30,
                            HasHours = true,
                            HasQuantity = false,
                            Icon = "organizing.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Organizing Service",
                            Price = 30m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8118),
                            Description = "Washing and folding service",
                            DisplayOrder = 7,
                            Duration = 45,
                            HasHours = false,
                            HasQuantity = true,
                            Icon = "laundry.png",
                            IsActive = true,
                            IsAvailableForAll = false,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Laundry Service",
                            Price = 25m,
                            PriceMultiplier = 1.0m,
                            ServiceTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8120),
                            Description = "Deep cleaning inside and outside",
                            DisplayOrder = 8,
                            Duration = 30,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "fridge-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Refrigerator Cleaning",
                            Price = 35m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8122),
                            Description = "Deep cleaning of oven interior",
                            DisplayOrder = 9,
                            Duration = 45,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "oven-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Oven Cleaning",
                            Price = 40m,
                            PriceMultiplier = 1.0m
                        });
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PurchasedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PurchasedByUserId");

                    b.ToTable("GiftCards");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCardUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountUsed")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BalanceAfterUsage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("GiftCardId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiftCardId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("GiftCardUsages");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ApartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AptSuite")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EntryMethod")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("GiftCardAmountUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("GiftCardCode")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaidsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("ServiceTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubscriptionDiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("ExtraServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExtraServiceId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderExtraServices");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderServices");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUsagePerUser")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRangeInput")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int?>("MinValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ServiceKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ServiceRelationType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("StepValue")
                        .HasColumnType("int");

                    b.Property<int>("TimeDuration")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceKey");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 25m,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8014),
                            DisplayOrder = 1,
                            InputType = "dropdown",
                            IsActive = true,
                            IsRangeInput = false,
                            MaxValue = 6,
                            MinValue = 0,
                            Name = "Bedrooms",
                            ServiceKey = "bedrooms",
                            ServiceTypeId = 1,
                            StepValue = 1,
                            TimeDuration = 30
                        },
                        new
                        {
                            Id = 2,
                            Cost = 35m,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8021),
                            DisplayOrder = 2,
                            InputType = "dropdown",
                            IsActive = true,
                            IsRangeInput = false,
                            MaxValue = 5,
                            MinValue = 1,
                            Name = "Bathrooms",
                            ServiceKey = "bathrooms",
                            ServiceTypeId = 1,
                            StepValue = 1,
                            TimeDuration = 45
                        },
                        new
                        {
                            Id = 3,
                            Cost = 0.10m,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8027),
                            DisplayOrder = 3,
                            InputType = "slider",
                            IsActive = true,
                            IsRangeInput = true,
                            MaxValue = 5000,
                            MinValue = 400,
                            Name = "Square Feet",
                            ServiceKey = "sqft",
                            ServiceTypeId = 1,
                            StepValue = 100,
                            TimeDuration = 1,
                            Unit = "per sqft"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 40m,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8065),
                            DisplayOrder = 1,
                            InputType = "dropdown",
                            IsActive = true,
                            IsRangeInput = false,
                            MaxValue = 10,
                            MinValue = 1,
                            Name = "Cleaners",
                            ServiceKey = "cleaners",
                            ServiceRelationType = "cleaner",
                            ServiceTypeId = 2,
                            StepValue = 1,
                            TimeDuration = 0,
                            Unit = "per hour"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 0m,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 262, DateTimeKind.Local).AddTicks(8068),
                            DisplayOrder = 2,
                            InputType = "dropdown",
                            IsActive = true,
                            IsRangeInput = false,
                            MaxValue = 8,
                            MinValue = 2,
                            Name = "Hours",
                            ServiceKey = "hours",
                            ServiceRelationType = "hours",
                            ServiceTypeId = 2,
                            StepValue = 1,
                            TimeDuration = 60
                        });
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 120m,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 261, DateTimeKind.Local).AddTicks(6124),
                            Description = "Complete home cleaning service",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Residential Cleaning"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 200m,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 261, DateTimeKind.Local).AddTicks(6127),
                            Description = "Professional office cleaning service",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Office Cleaning"
                        });
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.SpecialOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeColor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("RequiresFirstTimeCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SpecialOffers");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SubscriptionDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 261, DateTimeKind.Local).AddTicks(5877),
                            Description = "Single cleaning service",
                            DiscountPercentage = 0m,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "One Time",
                            SubscriptionDays = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 261, DateTimeKind.Local).AddTicks(5894),
                            Description = "Cleaning every week",
                            DiscountPercentage = 15m,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Weekly",
                            SubscriptionDays = 7
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 261, DateTimeKind.Local).AddTicks(5896),
                            Description = "Cleaning every two weeks",
                            DiscountPercentage = 10m,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Bi-Weekly",
                            SubscriptionDays = 14
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 21, 17, 17, 57, 261, DateTimeKind.Local).AddTicks(5897),
                            Description = "Cleaning once a month",
                            DiscountPercentage = 5m,
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Monthly",
                            SubscriptionDays = 30
                        });
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalAuthId")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("FirstTimeOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastOrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.UserSpecialOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SpecialOfferId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UsedOnOrderId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialOfferId");

                    b.HasIndex("UsedOnOrderId");

                    b.HasIndex("UserId", "SpecialOfferId")
                        .IsUnique();

                    b.ToTable("UserSpecialOffers");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Apartment", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany("Apartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.AuditLog", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ExtraService", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.ServiceType", "ServiceType")
                        .WithMany("ExtraServices")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCard", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.User", "PurchasedByUser")
                        .WithMany()
                        .HasForeignKey("PurchasedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchasedByUser");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCardUsage", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.GiftCard", "GiftCard")
                        .WithMany("GiftCardUsages")
                        .HasForeignKey("GiftCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiftCard");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Order", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DreamCleaningBackend.Models.ServiceType", "ServiceType")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Subscription", "Subscription")
                        .WithMany("Orders")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("ServiceType");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderExtraService", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.ExtraService", "ExtraService")
                        .WithMany("OrderExtraServices")
                        .HasForeignKey("ExtraServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Order", "Order")
                        .WithMany("OrderExtraServices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraService");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderService", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.Order", "Order")
                        .WithMany("OrderServices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Service", "Service")
                        .WithMany("OrderServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Service", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.ServiceType", "ServiceType")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.User", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.UserSpecialOffer", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.SpecialOffer", "SpecialOffer")
                        .WithMany("UserSpecialOffers")
                        .HasForeignKey("SpecialOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Order", "UsedOnOrder")
                        .WithMany()
                        .HasForeignKey("UsedOnOrderId");

                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany("UserSpecialOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecialOffer");

                    b.Navigation("UsedOnOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ExtraService", b =>
                {
                    b.Navigation("OrderExtraServices");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCard", b =>
                {
                    b.Navigation("GiftCardUsages");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Order", b =>
                {
                    b.Navigation("OrderExtraServices");

                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Service", b =>
                {
                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ServiceType", b =>
                {
                    b.Navigation("ExtraServices");

                    b.Navigation("Orders");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.SpecialOffer", b =>
                {
                    b.Navigation("UserSpecialOffers");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Subscription", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.User", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Orders");

                    b.Navigation("UserSpecialOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
