// <auto-generated />
using System;
using DreamCleaningBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamCleaningBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250914212512_AddScheduledMailsFeature")]
    partial class AddScheduledMailsFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DreamCleaningBackend.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AptSuite")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("HasHours")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasQuantity")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAvailableForAll")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeepCleaning")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSameDayService")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSuperDeepCleaning")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ExtraServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6729),
                            Description = "Thorough cleaning of all surfaces and hard-to-reach areas",
                            DisplayOrder = 1,
                            Duration = 60m,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "deep-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = true,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Deep Cleaning",
                            Price = 50m,
                            PriceMultiplier = 1.5m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6734),
                            Description = "Most intensive cleaning service available",
                            DisplayOrder = 2,
                            Duration = 120m,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "super-deep-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = true,
                            Name = "Super Deep Cleaning",
                            Price = 100m,
                            PriceMultiplier = 2.0m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6737),
                            Description = "Get your cleaning done today",
                            DisplayOrder = 3,
                            Duration = 0m,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "same-day.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = true,
                            IsSuperDeepCleaning = false,
                            Name = "Same Day Service",
                            Price = 75m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6739),
                            Description = "Interior window cleaning",
                            DisplayOrder = 4,
                            Duration = 20m,
                            HasHours = false,
                            HasQuantity = true,
                            Icon = "window-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Window Cleaning",
                            Price = 15m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6742),
                            Description = "Spot cleaning of walls",
                            DisplayOrder = 5,
                            Duration = 30m,
                            HasHours = false,
                            HasQuantity = true,
                            Icon = "wall-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Wall Cleaning",
                            Price = 20m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6746),
                            Description = "Professional organizing of your space",
                            DisplayOrder = 6,
                            Duration = 30m,
                            HasHours = true,
                            HasQuantity = false,
                            Icon = "organizing.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Organizing Service",
                            Price = 30m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6749),
                            Description = "Washing and folding service",
                            DisplayOrder = 7,
                            Duration = 45m,
                            HasHours = false,
                            HasQuantity = true,
                            Icon = "laundry.png",
                            IsActive = true,
                            IsAvailableForAll = false,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Laundry Service",
                            Price = 25m,
                            PriceMultiplier = 1.0m,
                            ServiceTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6763),
                            Description = "Deep cleaning inside and outside",
                            DisplayOrder = 8,
                            Duration = 30m,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "fridge-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Refrigerator Cleaning",
                            Price = 35m,
                            PriceMultiplier = 1.0m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6765),
                            Description = "Deep cleaning of oven interior",
                            DisplayOrder = 9,
                            Duration = 45m,
                            HasHours = false,
                            HasQuantity = false,
                            Icon = "oven-cleaning.png",
                            IsActive = true,
                            IsAvailableForAll = true,
                            IsDeepCleaning = false,
                            IsSameDayService = false,
                            IsSuperDeepCleaning = false,
                            Name = "Oven Cleaning",
                            Price = 40m,
                            PriceMultiplier = 1.0m
                        });
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PurchasedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PurchasedByUserId");

                    b.ToTable("GiftCards");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("GiftCardConfigs");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCardUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountUsed")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BalanceAfterUsage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("GiftCardId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiftCardId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("GiftCardUsages");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.MaintenanceMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StartedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceModes");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CleanerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CleanerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ApartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AptSuite")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CompanyDevelopmentTips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EntryMethod")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("GiftCardAmountUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("GiftCardCode")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<decimal>("InitialCompanyDevelopmentTips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialSubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialTips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaidsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("ServiceTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SpecialOfferName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubscriptionDiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDuration")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserSpecialOfferId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderCleaner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int>("CleanerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("TipsForCleaner")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("CleanerId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderCleaners");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ExtraServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExtraServiceId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderExtraServices");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderServices");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderUpdateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdditionalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<decimal>("NewCompanyDevelopmentTips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewSubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewTips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalCompanyDevelopmentTips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalSubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalTips")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UpdateNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("OrderUpdateHistories");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PollAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PollQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("PollSubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollQuestionId");

                    b.HasIndex("PollSubmissionId");

                    b.ToTable("PollAnswers");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PollQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Options")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("PollQuestions");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PollSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AptSuite")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("PollSubmissions");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUsagePerUser")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ScheduledMail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int?>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NextScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("ScheduledTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TargetRoles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TimesSent")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WeekOfMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("NextScheduledAt")
                        .HasDatabaseName("IX_ScheduledMails_NextScheduledAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ScheduledMails_Status");

                    b.ToTable("ScheduledMails");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.SentMailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RecipientRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ScheduledMailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledMailId", "SentAt")
                        .HasDatabaseName("IX_SentMailLogs_MailId_SentAt");

                    b.ToTable("SentMailLogs");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRangeInput")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int?>("MinValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ServiceKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ServiceRelationType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("StepValue")
                        .HasColumnType("int");

                    b.Property<decimal>("TimeDuration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceKey");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 25m,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6517),
                            DisplayOrder = 1,
                            InputType = "dropdown",
                            IsActive = true,
                            IsRangeInput = false,
                            MaxValue = 6,
                            MinValue = 0,
                            Name = "Bedrooms",
                            ServiceKey = "bedrooms",
                            ServiceTypeId = 1,
                            StepValue = 1,
                            TimeDuration = 30m
                        },
                        new
                        {
                            Id = 2,
                            Cost = 35m,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6522),
                            DisplayOrder = 2,
                            InputType = "dropdown",
                            IsActive = true,
                            IsRangeInput = false,
                            MaxValue = 5,
                            MinValue = 1,
                            Name = "Bathrooms",
                            ServiceKey = "bathrooms",
                            ServiceTypeId = 1,
                            StepValue = 1,
                            TimeDuration = 45m
                        },
                        new
                        {
                            Id = 3,
                            Cost = 0.10m,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6529),
                            DisplayOrder = 3,
                            InputType = "slider",
                            IsActive = true,
                            IsRangeInput = true,
                            MaxValue = 5000,
                            MinValue = 400,
                            Name = "Square Feet",
                            ServiceKey = "sqft",
                            ServiceTypeId = 1,
                            StepValue = 100,
                            TimeDuration = 1m,
                            Unit = "per sqft"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 40m,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6668),
                            DisplayOrder = 1,
                            InputType = "dropdown",
                            IsActive = true,
                            IsRangeInput = false,
                            MaxValue = 10,
                            MinValue = 1,
                            Name = "Cleaners",
                            ServiceKey = "cleaners",
                            ServiceRelationType = "cleaner",
                            ServiceTypeId = 2,
                            StepValue = 1,
                            TimeDuration = 0m,
                            Unit = "per hour"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 0m,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 99, DateTimeKind.Utc).AddTicks(6672),
                            DisplayOrder = 2,
                            InputType = "dropdown",
                            IsActive = true,
                            IsRangeInput = false,
                            MaxValue = 8,
                            MinValue = 2,
                            Name = "Hours",
                            ServiceKey = "hours",
                            ServiceRelationType = "hours",
                            ServiceTypeId = 2,
                            StepValue = 1,
                            TimeDuration = 60m
                        });
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("HasPoll")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TimeDuration")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 120m,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 97, DateTimeKind.Utc).AddTicks(206),
                            Description = "Complete home cleaning service",
                            DisplayOrder = 1,
                            HasPoll = false,
                            IsActive = true,
                            IsCustom = false,
                            Name = "Residential Cleaning",
                            TimeDuration = 90m
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 200m,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 97, DateTimeKind.Utc).AddTicks(210),
                            Description = "Professional office cleaning service",
                            DisplayOrder = 2,
                            HasPoll = false,
                            IsActive = true,
                            IsCustom = false,
                            Name = "Office Cleaning",
                            TimeDuration = 120m
                        });
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.SpecialOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeColor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("RequiresFirstTimeCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SpecialOffers");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SubscriptionDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 96, DateTimeKind.Utc).AddTicks(9618),
                            Description = "Single cleaning service",
                            DiscountPercentage = 0m,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "One Time",
                            SubscriptionDays = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 96, DateTimeKind.Utc).AddTicks(9625),
                            Description = "Cleaning every week",
                            DiscountPercentage = 15m,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Weekly",
                            SubscriptionDays = 7
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 96, DateTimeKind.Utc).AddTicks(9628),
                            Description = "Cleaning every two weeks",
                            DiscountPercentage = 10m,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Bi-Weekly",
                            SubscriptionDays = 14
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 14, 21, 25, 11, 96, DateTimeKind.Utc).AddTicks(9630),
                            Description = "Cleaning once a month",
                            DiscountPercentage = 5m,
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Monthly",
                            SubscriptionDays = 30
                        });
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailChangeToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EmailChangeTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalAuthId")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("FirstTimeOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastOrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("longtext");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.UserSpecialOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SpecialOfferId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UsedOnOrderId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialOfferId");

                    b.HasIndex("UsedOnOrderId");

                    b.HasIndex("UserId", "SpecialOfferId")
                        .IsUnique();

                    b.ToTable("UserSpecialOffers");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.WebhookEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EventId");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Apartment", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany("Apartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.AuditLog", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ExtraService", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.ServiceType", "ServiceType")
                        .WithMany("ExtraServices")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCard", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.User", "PurchasedByUser")
                        .WithMany()
                        .HasForeignKey("PurchasedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchasedByUser");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCardUsage", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.GiftCard", "GiftCard")
                        .WithMany("GiftCardUsages")
                        .HasForeignKey("GiftCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiftCard");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.NotificationLog", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.User", "Cleaner")
                        .WithMany()
                        .HasForeignKey("CleanerId");

                    b.HasOne("DreamCleaningBackend.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("DreamCleaningBackend.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cleaner");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Order", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DreamCleaningBackend.Models.ServiceType", "ServiceType")
                        .WithMany("Orders")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Subscription", "Subscription")
                        .WithMany("Orders")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("ServiceType");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderCleaner", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.User", "Cleaner")
                        .WithMany()
                        .HasForeignKey("CleanerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Order", "Order")
                        .WithMany("OrderCleaners")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Cleaner");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderExtraService", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.ExtraService", "ExtraService")
                        .WithMany("OrderExtraServices")
                        .HasForeignKey("ExtraServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Order", "Order")
                        .WithMany("OrderExtraServices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraService");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderService", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.Order", "Order")
                        .WithMany("OrderServices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Service", "Service")
                        .WithMany("OrderServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.OrderUpdateHistory", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.Order", "Order")
                        .WithMany("UpdateHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PollAnswer", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.PollQuestion", "PollQuestion")
                        .WithMany("PollAnswers")
                        .HasForeignKey("PollQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.PollSubmission", "PollSubmission")
                        .WithMany("PollAnswers")
                        .HasForeignKey("PollSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PollQuestion");

                    b.Navigation("PollSubmission");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PollQuestion", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.ServiceType", "ServiceType")
                        .WithMany("PollQuestions")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PollSubmission", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ServiceType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ScheduledMail", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.SentMailLog", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.ScheduledMail", "ScheduledMail")
                        .WithMany("SentMailLogs")
                        .HasForeignKey("ScheduledMailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledMail");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Service", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.ServiceType", "ServiceType")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.User", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.UserSpecialOffer", b =>
                {
                    b.HasOne("DreamCleaningBackend.Models.SpecialOffer", "SpecialOffer")
                        .WithMany("UserSpecialOffers")
                        .HasForeignKey("SpecialOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamCleaningBackend.Models.Order", "UsedOnOrder")
                        .WithMany()
                        .HasForeignKey("UsedOnOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DreamCleaningBackend.Models.User", "User")
                        .WithMany("UserSpecialOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecialOffer");

                    b.Navigation("UsedOnOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ExtraService", b =>
                {
                    b.Navigation("OrderExtraServices");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.GiftCard", b =>
                {
                    b.Navigation("GiftCardUsages");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Order", b =>
                {
                    b.Navigation("OrderCleaners");

                    b.Navigation("OrderExtraServices");

                    b.Navigation("OrderServices");

                    b.Navigation("UpdateHistory");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PollQuestion", b =>
                {
                    b.Navigation("PollAnswers");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.PollSubmission", b =>
                {
                    b.Navigation("PollAnswers");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ScheduledMail", b =>
                {
                    b.Navigation("SentMailLogs");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Service", b =>
                {
                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.ServiceType", b =>
                {
                    b.Navigation("ExtraServices");

                    b.Navigation("Orders");

                    b.Navigation("PollQuestions");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.SpecialOffer", b =>
                {
                    b.Navigation("UserSpecialOffers");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.Subscription", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DreamCleaningBackend.Models.User", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("Orders");

                    b.Navigation("UserSpecialOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
