// <auto-generated />
using System;
using DreamCleaningBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamCleaningBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260125120000_ReAddScheduledMailsAndSentMailLogs")]
    partial class ReAddScheduledMailsAndSentMailLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is the same as ApplicationDbContextModelSnapshot after this migration.
            // The snapshot is updated separately to include ScheduledMail and SentMailLog.
        }
    }
}
